#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace Exposure.EditorTools
{
    /// <summary>
    /// Builds the polished dressing for the acrophobia scene: a distant city skyline, a ground
    /// plane far below, and depth fog.
    ///
    /// Deliberately a generator rather than saved scene content. The city prefabs come from a
    /// commercial pack under Assets/3rd Party Assets/, which is gitignored -- baking those
    /// references into the committed scene would leave anyone cloning the repository with a
    /// scene full of missing objects. Generating on demand keeps the committed scene the clean
    /// blockout, and the polished build is one menu click away for whoever has the pack.
    ///
    /// Run "Build City Backdrop" before the polished build, "Clear City Backdrop" before the
    /// blockout build or before committing.
    /// </summary>
    public static class PolishedEnvironmentSetup
    {
        private const string BackdropName = "CityBackdrop";
        private const string BuildingsPath =
            "Assets/3rd Party Assets/POLYBOX/hazelwoodloft/CITY_DATA_NEW/new_prefabs/" +
            "prefabs_day_buildings_skyscrapers";
        private const string BirdsPath = "Assets/3rd Party Assets/POLYBOX/hazelwoodloft/Animation";
        private const string MatsPath  = "Assets/3rd Party Assets/Mats";

        /// <summary>
        /// Texture budget per surface. 2K only where the participant stands right against the
        /// surface and can see it at arm's length; everything further away gets 1K, where the
        /// difference is invisible but the memory is not. Both are ASTC on Android.
        /// </summary>
        private const int NearTextureSize = 2048;
        private const int FarTextureSize  = 1024;

        private const string MaterialPrefKeyPrefix = "Exposure.BlockoutMaterial.";
        private const string BuiltInMaterialSentinel = "<builtin>";

        /// <summary>Surfaces the polish pass retextures, and therefore has to be able to put back.</summary>
        private static readonly string[] TexturedSurfaceNames =
            { "Wall", "RailingSolid", "SurfaceSolid", "SurfaceGrating" };

        /// <summary>
        /// Ground materials are shared by many objects, so they are retextured at the *material*
        /// rather than the renderer: one edit reaches every road segment at once. They are
        /// regenerated by the height-cue generator anyway, so nothing needs restoring.
        /// </summary>
        private const string BlockoutMaterialFolder = "Assets/_Exposure/Materials";

        [MenuItem("Exposure/Polish/Build City Backdrop")]
        public static void BuildBackdrop()
        {
            if (AcrophobiaSceneSetup.RefuseDuringPlayMode()) return;

            var rig = GameObject.Find("PlatformRig");
            if (rig == null)
            {
                Debug.LogError("[Exposure] PlatformRig not found -- open Exposure_Acrophobia.unity first.");
                return;
            }

            ClearBackdrop();

            var prefabs = LoadBuildingPrefabs();
            if (prefabs.Count == 0)
            {
                Debug.LogError($"[Exposure] No building prefabs found under {BuildingsPath}. " +
                               "The POLYBOX pack is gitignored -- import it via the Asset Store " +
                               "(Package Manager > My Assets) before running this.");
                return;
            }

            // Parented to PlatformRig because that is what moves during the elevator ride: the
            // world travels down past the participant, so the city has to travel with it.
            var root = new GameObject(BackdropName);
            Undo.RegisterCreatedObjectUndo(root, "Build City Backdrop");
            root.transform.SetParent(rig.transform, false);

            BuildGroundPlane(root.transform);
            ScatterBuildings(root.transform, prefabs);
            ScatterBirds(root.transform);
            ApplySurfaceTextures();
            ApplyDepthFog();

            EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
            Debug.Log($"[Exposure] City backdrop built from {prefabs.Count} building prefabs. " +
                      "Remember to clear it before committing or before the blockout build.");
        }

        [MenuItem("Exposure/Polish/Clear City Backdrop")]
        public static void ClearBackdrop()
        {
            var existing = GameObject.Find(BackdropName);
            while (existing != null)
            {
                Undo.DestroyObjectImmediate(existing);
                existing = GameObject.Find(BackdropName);
            }

            RestoreBlockoutMaterials();
            EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
        }

        /// <summary>
        /// Puts back the materials the textured surfaces replaced.
        ///
        /// Without this, clearing the backdrop leaves the polished stone and steel on the
        /// platform, so the blockout build quietly ships looking polished -- the exact failure
        /// the clear-before-commit rule exists to prevent, just moved one step down.
        ///
        /// The originals are remembered in EditorPrefs rather than a field: assembly reloads
        /// wipe statics, and the gap between building and clearing is usually several reloads
        /// wide.
        /// </summary>
        private static void RestoreBlockoutMaterials()
        {
            foreach (var name in TexturedSurfaceNames)
            {
                string key = MaterialPrefKeyPrefix + name;
                if (!EditorPrefs.HasKey(key)) continue;

                var go = GameObject.Find(name);
                var renderer = go != null ? go.GetComponent<Renderer>() : null;
                if (renderer != null)
                {
                    string stored = EditorPrefs.GetString(key);
                    renderer.sharedMaterial = stored == BuiltInMaterialSentinel
                        ? DefaultLitMaterial()
                        : AssetDatabase.LoadAssetAtPath<Material>(stored) ?? DefaultLitMaterial();
                }
                EditorPrefs.DeleteKey(key);
            }
        }

        private static List<GameObject> LoadBuildingPrefabs()
        {
            var prefabs = new List<GameObject>();
            if (!Directory.Exists(BuildingsPath)) return prefabs;

            foreach (var guid in AssetDatabase.FindAssets("t:Prefab", new[] { BuildingsPath }))
            {
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(AssetDatabase.GUIDToAssetPath(guid));
                if (prefab != null) prefabs.Add(prefab);
            }
            return prefabs;
        }

        /// <summary>
        /// The street far below, so looking down reads as "ground a long way away" rather than
        /// "void". Sits at PlatformRig's own origin: the rig is the world, and it starts level
        /// with the participant at the ground floor and travels down as they ascend, so y=0 here
        /// is street level by construction.
        /// </summary>
        private static void BuildGroundPlane(Transform parent)
        {
            var ground = GameObject.CreatePrimitive(PrimitiveType.Plane);
            ground.name = "GroundPlane";
            ground.transform.SetParent(parent, false);
            ground.transform.localPosition = new Vector3(0f, -0.2f, 0f);
            ground.transform.localScale = new Vector3(60f, 1f, 60f); // 600 m across
            Object.DestroyImmediate(ground.GetComponent<Collider>());

            var renderer = ground.GetComponent<Renderer>();
            if (renderer != null) renderer.sharedMaterial = MakeMaterial("GroundFar", new Color(0.18f, 0.19f, 0.21f));
        }

        /// <summary>
        /// Buildings in a ring around the tower, standing on the street plane.
        ///
        /// The pack is authored at city scale -- the prefabs measure 100-270 units tall, so at
        /// their native size a single one would swallow a ten-storey building. Scaled down to
        /// roughly 25-70 m and pushed out to 40-180 m, they read as an ordinary skyline seen
        /// from a rooftop, which is the whole point: the height has to feel like a real place.
        ///
        /// Materials are left exactly as the pack ships them. They are built-in-pipeline
        /// materials and will render magenta until they are converted to URP -- that conversion
        /// is a deliberate manual step (Window > Rendering > Render Pipeline Converter >
        /// "Built-in to URP" > Material Upgrade), not something this generator should force.
        /// </summary>
        private static void ScatterBuildings(Transform parent, List<GameObject> prefabs)
        {
            const int count = 40;
            const float minRadius = 40f;
            const float maxRadius = 180f;

            Random.InitState(20260806); // stable layout across runs -- the video should not change

            for (int i = 0; i < count; i++)
            {
                var prefab = prefabs[Random.Range(0, prefabs.Count)];
                var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab, parent);
                if (instance == null) continue;

                float angle = (i / (float)count) * Mathf.PI * 2f + Random.Range(-0.06f, 0.06f);
                float radius = Random.Range(minRadius, maxRadius);

                // Prefab pivots sit at the building's base, so y = 0 puts them on the street.
                instance.transform.localPosition = new Vector3(
                    Mathf.Cos(angle) * radius,
                    0f,
                    Mathf.Sin(angle) * radius);
                instance.transform.localRotation = Quaternion.Euler(0f, Random.Range(0f, 360f), 0f);

                float footprint = Random.Range(0.16f, 0.30f);
                instance.transform.localScale = new Vector3(footprint, Random.Range(0.14f, 0.32f), footprint);

                // Distant silhouettes are never touched, and colliders on 40 buildings cost
                // physics time for nothing.
                foreach (var collider in instance.GetComponentsInChildren<Collider>())
                    Object.DestroyImmediate(collider);
            }
        }

        /// <summary>
        /// Birds circling below and level with the platform.
        ///
        /// Seeing birds *below* eye level is a cue with no ground-level equivalent, and unlike
        /// the abstract rising spheres it is something people have actually experienced from a
        /// high window. Animated prefabs from the POLYBOX pack, so this lives in the polished
        /// path only -- the pack is gitignored and the blockout must stay free of it.
        /// </summary>
        private static void ScatterBirds(Transform parent)
        {
            var prefabs = new List<GameObject>();
            foreach (var guid in AssetDatabase.FindAssets("room5_bird", new[] { BirdsPath }))
            {
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(AssetDatabase.GUIDToAssetPath(guid));
                if (prefab != null) prefabs.Add(prefab);
            }

            if (prefabs.Count == 0)
            {
                Debug.Log($"[Exposure] No bird prefabs under {BirdsPath} -- skipped. " +
                          "They ship with the POLYBOX pack, which is gitignored.");
                return;
            }

            var birds = new GameObject("Birds");
            birds.transform.SetParent(parent, false);

            Random.InitState(1312);
            for (int i = 0; i < prefabs.Count * 4; i++)
            {
                var instance = (GameObject)PrefabUtility.InstantiatePrefab(
                    prefabs[i % prefabs.Count], birds.transform);
                if (instance == null) continue;

                // Close enough to read as birds. At 18-55 m they were a few pixels of animated
                // texture and went unnoticed entirely -- which wasted the one cue that has a
                // real-world size the eye already knows. Brought in to roughly the distance you
                // would actually see a bird from a balcony, biased to the open side.
                float angle = Random.Range(0f, Mathf.PI * 2f);
                float radius = Random.Range(7f, 22f);

                // Spread across the height the participant travels, so some are always below.
                instance.transform.localPosition = new Vector3(
                    Mathf.Cos(angle) * radius,
                    Random.Range(4f, 28f),
                    Mathf.Abs(Mathf.Sin(angle)) * radius + 4f);
                instance.transform.localRotation = Quaternion.Euler(0f, Random.Range(0f, 360f), 0f);

                foreach (var collider in instance.GetComponentsInChildren<Collider>())
                    Object.DestroyImmediate(collider);
            }
        }

        /// <summary>
        /// Textures the two surfaces the participant is actually close to: the lift car and the
        /// building wall right behind them.
        ///
        /// Only those two. Scale correctness and parallax carry the height far more than surface
        /// detail does, so texturing distant scenery would cost Quest 2 memory for something the
        /// eye cannot resolve — but a wall you are standing against reads as cardboard without a
        /// surface, and cardboard breaks the presence the whole exposure depends on.
        ///
        /// Textures come from the gitignored Mats collection, so this lives in the polish path.
        /// If they are missing the blockout materials simply stay as they are.
        /// </summary>
        private static void ApplySurfaceTextures()
        {
            if (!Directory.Exists(MatsPath))
            {
                Debug.Log($"[Exposure] No textures under {MatsPath} -- surfaces stay untextured. " +
                          "The Mats collection is gitignored.");
                return;
            }

            // The wall the participant stands against: board-marked concrete, which is what a
            // building of this kind is actually faced with -- and the only surface close enough
            // for 2K to be worth the memory.
            var facade = TexturedMaterial("Polish_Facade",
                baseMap:   $"{MatsPath}/Concrete/concrete_59_basecolor-2K.png",
                normalMap: $"{MatsPath}/Concrete/concrete_59_normal-2K.png",
                size: NearTextureSize, tiling: new Vector2(3f, 9f), smoothness: 0.2f);

            AssignTextured("Wall", facade);

            // The lift car and railings: brushed steel.
            var steel = TexturedMaterial("Polish_Steel",
                baseMap:   $"{MatsPath}/SteelGrey/Steel Grey_old_Base Color.jpeg",
                normalMap: $"{MatsPath}/SteelGrey/Steel Grey_old_Normal.jpeg",
                size: NearTextureSize, tiling: new Vector2(2f, 2f), smoothness: 0.62f, metallic: 0.85f);

            foreach (var name in new[] { "RailingSolid", "SurfaceSolid", "SurfaceGrating" })
                AssignTextured(name, steel);

            TextureGroundMaterials();

            Debug.Log("[Exposure] Surface textures applied to the near wall, the platform metal " +
                      "and the ground. Clear City Backdrop puts the blockout materials back.");
        }

        /// <summary>
        /// Puts real surfaces on the road, pavement and park below.
        ///
        /// All at 1K: they sit thirty metres down, where the eye resolves the *pattern* — the
        /// grain of asphalt, the joints between slabs — long before it resolves any detail. That
        /// pattern is what makes the drop read as a real street rather than coloured boxes, and
        /// it costs a quarter of the memory the near wall does.
        ///
        /// Edited on the shared materials rather than per renderer, so one change reaches every
        /// road segment at once. These materials are regenerated by the height-cue generator, so
        /// re-running "Setup Height Cues" is what puts the blockout colours back.
        /// </summary>
        private static void TextureGroundMaterials()
        {
            RetextureShared("Cue_Asphalt",
                $"{MatsPath}/Asphalt/asphalt_14_basecolor-1K.png",
                $"{MatsPath}/Asphalt/asphalt_14_normal-1K.png",
                tiling: new Vector2(8f, 14f), smoothness: 0.15f);

            RetextureShared("Cue_Pavement",
                $"{MatsPath}/Pavement/pavement_34 _basecolor-1K.png",
                $"{MatsPath}/Pavement/pavement_34 _normal-1K.png",
                tiling: new Vector2(16f, 16f), smoothness: 0.1f);

            RetextureShared("Cue_Neighbour",
                $"{MatsPath}/Concrete/concrete_59_basecolor-2K.png",
                $"{MatsPath}/Concrete/concrete_59_normal-2K.png",
                tiling: new Vector2(2f, 4f), smoothness: 0.2f, size: FarTextureSize);
        }

        /// <summary>Adds maps to an existing blockout material, keeping its tint as a base colour.</summary>
        private static void RetextureShared(string materialName, string baseMap, string normalMap,
                                            Vector2 tiling, float smoothness, int size = FarTextureSize)
        {
            var mat = AssetDatabase.LoadAssetAtPath<Material>($"{BlockoutMaterialFolder}/{materialName}.mat");
            if (mat == null) return;

            var albedo = ImportTexture(baseMap, size, isNormalMap: false);
            if (albedo == null) return;

            mat.SetTexture("_BaseMap", albedo);
            mat.SetTextureScale("_BaseMap", tiling);

            var normal = ImportTexture(normalMap, size, isNormalMap: true);
            if (normal != null)
            {
                mat.SetTexture("_BumpMap", normal);
                mat.SetTextureScale("_BumpMap", tiling);
                mat.EnableKeyword("_NORMALMAP");
            }

            // A white base tint, or the blockout colour would multiply the texture into mud.
            mat.SetColor("_BaseColor", Color.white);
            mat.SetFloat("_Smoothness", smoothness);
            EditorUtility.SetDirty(mat);
        }

        /// <summary>
        /// Swaps in a polished material, noting what was there so the blockout can be restored.
        /// </summary>
        private static void AssignTextured(string objectName, Material polished)
        {
            if (polished == null) return;

            var go = GameObject.Find(objectName);
            var renderer = go != null ? go.GetComponent<Renderer>() : null;
            if (renderer == null) return;

            string key = MaterialPrefKeyPrefix + objectName;
            if (!EditorPrefs.HasKey(key))
            {
                // Built-in materials (the default URP Lit these primitives ship with) have no
                // asset path, so an empty string here is a real answer, not a failure -- it
                // means "restore the default", and the restore side has to understand that.
                string path = renderer.sharedMaterial != null
                    ? AssetDatabase.GetAssetPath(renderer.sharedMaterial)
                    : "";
                EditorPrefs.SetString(key, string.IsNullOrEmpty(path) ? BuiltInMaterialSentinel : path);
            }

            renderer.sharedMaterial = polished;
        }

        /// <summary>
        /// Builds a URP Lit material from a base and normal map, forcing the import size down to
        /// the given budget so a 6000 px source cannot quietly ship at full resolution.
        /// </summary>
        private static Material TexturedMaterial(string name, string baseMap, string normalMap,
                                                 int size, Vector2 tiling, float smoothness,
                                                 float metallic = 0f)
        {
            var albedo = ImportTexture(baseMap, size, isNormalMap: false);
            if (albedo == null)
            {
                Debug.LogWarning($"[Exposure] Texture not found: {baseMap} -- {name} skipped.");
                return null;
            }
            var normal = ImportTexture(normalMap, size, isNormalMap: true);

            const string folder = "Assets/_Exposure/Materials";
            Directory.CreateDirectory(folder);
            string path = $"{folder}/{name}.mat";

            var mat = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (mat == null)
            {
                var shader = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
                mat = new Material(shader) { name = name };
                AssetDatabase.CreateAsset(mat, path);
            }

            mat.SetTexture("_BaseMap", albedo);
            mat.SetTextureScale("_BaseMap", tiling);
            if (normal != null)
            {
                mat.SetTexture("_BumpMap", normal);
                mat.SetTextureScale("_BumpMap", tiling);
                mat.EnableKeyword("_NORMALMAP");
            }
            mat.SetFloat("_Smoothness", smoothness);
            mat.SetFloat("_Metallic", metallic);
            EditorUtility.SetDirty(mat);
            return mat;
        }

        private static Texture2D ImportTexture(string path, int maxSize, bool isNormalMap)
        {
            if (string.IsNullOrEmpty(path) || !File.Exists(path)) return null;

            var importer = AssetImporter.GetAtPath(path) as TextureImporter;
            if (importer != null)
            {
                bool changed = false;
                if (importer.maxTextureSize != maxSize) { importer.maxTextureSize = maxSize; changed = true; }

                var wanted = isNormalMap ? TextureImporterType.NormalMap : TextureImporterType.Default;
                if (importer.textureType != wanted) { importer.textureType = wanted; changed = true; }

                if (changed)
                {
                    importer.SaveAndReimport();
                }
            }

            return AssetDatabase.LoadAssetAtPath<Texture2D>(path);
        }

        /// <summary>
        /// Depth fog does three jobs at once here: it sells scale, hides how little detail the
        /// far buildings carry, and lets the far clip plane come in closer, which is what keeps
        /// this affordable on a Quest 2. Tuned to still show the nearest ring of buildings
        /// clearly -- fog that swallows them would remove the very cue that conveys height.
        /// </summary>
        private static void ApplyDepthFog()
        {
            RenderSettings.fog = true;

            // Exponential-squared rather than linear. Linear fog thickens at a constant rate,
            // which is not how air behaves and reads as a grey curtain hung at a fixed distance
            // -- the giveaway is a visible band where it starts. Real haze accumulates with the
            // amount of air you look through, so it stays almost clear nearby and closes in
            // gradually; squared exponential is the cheap approximation of that.
            RenderSettings.fogMode = FogMode.ExponentialSquared;
            RenderSettings.fogDensity = 0.0055f;

            // Slightly blue and lighter than the buildings, so distance reads as air rather
            // than as dirt, and matched to the horizon so the two do not meet in a seam.
            RenderSettings.fogColor = new Color(0.70f, 0.77f, 0.86f);
        }

        /// <summary>The plain URP Lit material Unity primitives are created with.</summary>
        private static Material DefaultLitMaterial()
            => AssetDatabase.GetBuiltinExtraResource<Material>("Default-Material.mat")
               ?? new Material(Shader.Find("Universal Render Pipeline/Lit"));

        private static Material MakeMaterial(string name, Color color)
        {
            var shader = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
            var material = new Material(shader) { name = name };
            material.color = color;

            const string folder = "Assets/_Exposure/Materials";
            Directory.CreateDirectory(folder);
            string path = $"{folder}/{name}.mat";

            var existing = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (existing != null) return existing;

            AssetDatabase.CreateAsset(material, path);
            return material;
        }
    }
}
#endif
