using System;
using System.Collections.Generic;
using UnityEngine;

namespace Exposure
{
    /// <summary>
    /// A single catastrophic cognition the participant can predict before a task.
    /// </summary>
    [Serializable]
    public struct FearedOutcome
    {
        [Tooltip("Stable id used in the session log -- keep unchanged once data exists.")]
        public string id;

        [TextArea(1, 3)]
        [Tooltip("Wording shown to the participant, first person.")]
        public string text;
    }

    /// <summary>
    /// Swappable list of height-specific catastrophic cognitions offered for selection
    /// before each task (behavioural-experiment format: state the prediction, then test it).
    ///
    /// Selection instead of free text is deliberate -- typing via hand tracking inside the
    /// headset is impractical.
    ///
    /// IMPORTANT: the default items generated by the editor menu are PLACEHOLDERS derived
    /// from common findings in the acrophobia literature. They are not a validated item
    /// pool. Replace them with items from a validated instrument (Acrophobia Questionnaire
    /// thought scale, or Heights Interpretation Questionnaire) before any use with real
    /// participants. Because this is an asset rather than hard-coded data, swapping the
    /// list requires no code change.
    /// </summary>
    [CreateAssetMenu(fileName = "FearedOutcomes_", menuName = "Exposure/Feared Outcome Catalog")]
    public class FearedOutcomeCatalog : ScriptableObject
    {
        [Tooltip("Which instrument these items come from. Keep accurate -- it ends up in the log.")]
        public string sourceInstrument = "PLACEHOLDER - not a validated item pool";

        public List<FearedOutcome> outcomes = new List<FearedOutcome>();

        public bool TryGet(int index, out FearedOutcome outcome)
        {
            if (index >= 0 && index < outcomes.Count)
            {
                outcome = outcomes[index];
                return true;
            }
            outcome = default;
            return false;
        }
    }
}
